/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => GraphSourceColorPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// sourceDetector.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  sourceFolder: "wiki/sources",
  groupColors: {
    "gov-report": "#4A90D9",
    "april-meeting": "#F5A623"
  }
};
var SourceDetector = class {
  constructor(app, settings) {
    this.sourceCache = /* @__PURE__ */ new Map();
    // 源点出链指向的笔记 → 该笔记属于源点的子节点
    this.childMap = /* @__PURE__ */ new Map();
    this.app = app;
    this.settings = settings;
    this.buildSourceCache();
  }
  /**
   * 构建源点缓存
   * 包含所有有 group 的源点，即使没有配置颜色
   * 无颜色的源点 color 为空串，不参与着色但仍在缓存中以便识别
   */
  buildSourceCache() {
    var _a;
    this.sourceCache.clear();
    this.childMap.clear();
    const files = this.app.vault.getMarkdownFiles();
    const sourceFolder = this.settings.sourceFolder;
    for (const file of files) {
      if (file.path.startsWith(sourceFolder)) {
        const cache = this.app.metadataCache.getFileCache(file);
        const group = (_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a.group;
        if (group) {
          this.sourceCache.set(file.path, {
            file,
            path: file.path,
            group,
            color: this.getGroupColor(group)
          });
        }
      }
    }
    for (const [sourcePath, sourceInfo] of this.sourceCache) {
      const cache = this.app.metadataCache.getFileCache(sourceInfo.file);
      if (!(cache == null ? void 0 : cache.links))
        continue;
      for (const link of cache.links) {
        const resolved = this.app.metadataCache.getFirstLinkpathDest(link.link, sourcePath);
        if (!resolved)
          continue;
        const resolvedPath = resolved.path;
        if (this.sourceCache.has(resolvedPath))
          continue;
        if (!this.childMap.has(resolvedPath)) {
          this.childMap.set(resolvedPath, /* @__PURE__ */ new Set());
        }
        this.childMap.get(resolvedPath).add(sourcePath);
      }
    }
    const excludePaths = /* @__PURE__ */ new Set(["wiki/index.md"]);
    for (const file of files) {
      if (this.sourceCache.has(file.path))
        continue;
      if (excludePaths.has(file.path))
        continue;
      const cache = this.app.metadataCache.getFileCache(file);
      if (!(cache == null ? void 0 : cache.links))
        continue;
      for (const link of cache.links) {
        const resolved = this.app.metadataCache.getFirstLinkpathDest(link.link, file.path);
        if (!resolved)
          continue;
        if (!this.sourceCache.has(resolved.path))
          continue;
        if (!this.childMap.has(file.path)) {
          this.childMap.set(file.path, /* @__PURE__ */ new Set());
        }
        this.childMap.get(file.path).add(resolved.path);
      }
    }
    this.propagateSources();
  }
  /**
   * 沿 concept 之间的链接传播源点关系
   * BFS：已关联源点的节点，其出链指向的节点也继承该源点
   */
  propagateSources() {
    const queue = [];
    const visited = /* @__PURE__ */ new Set();
    for (const path of this.childMap.keys()) {
      queue.push(path);
      visited.add(path);
    }
    while (queue.length > 0) {
      const currentPath = queue.shift();
      const currentSources = this.childMap.get(currentPath);
      if (!currentSources || currentSources.size === 0)
        continue;
      const file = this.app.vault.getAbstractFileByPath(currentPath);
      if (!(file instanceof import_obsidian.TFile))
        continue;
      const cache = this.app.metadataCache.getFileCache(file);
      if (!(cache == null ? void 0 : cache.links))
        continue;
      for (const link of cache.links) {
        const resolved = this.app.metadataCache.getFirstLinkpathDest(link.link, currentPath);
        if (!resolved)
          continue;
        const resolvedPath = resolved.path;
        if (this.sourceCache.has(resolvedPath))
          continue;
        let changed = false;
        if (!this.childMap.has(resolvedPath)) {
          this.childMap.set(resolvedPath, /* @__PURE__ */ new Set());
        }
        const targetSources = this.childMap.get(resolvedPath);
        for (const sp of currentSources) {
          if (!targetSources.has(sp)) {
            targetSources.add(sp);
            changed = true;
          }
        }
        if (changed && !visited.has(resolvedPath)) {
          visited.add(resolvedPath);
          queue.push(resolvedPath);
        }
      }
    }
  }
  /**
   * 获取 group 对应的颜色，未配置返回空串
   */
  getGroupColor(group) {
    return this.settings.groupColors[group] || "";
  }
  /**
   * 检查文件是否为源点
   */
  isSourceFile(file) {
    return this.sourceCache.has(file.path);
  }
  /**
   * 检查路径是否为源点
   */
  isSourcePath(path) {
    return this.sourceCache.has(path);
  }
  /**
   * 获取源点信息
   */
  getSourceInfo(path) {
    return this.sourceCache.get(path);
  }
  /**
   * 获取所有源点
   */
  getAllSources() {
    return Array.from(this.sourceCache.values());
  }
  /**
   * 更新设置
   */
  updateSettings(settings) {
    this.settings = settings;
    this.buildSourceCache();
  }
  /**
   * 获取笔记关联的所有源点（基于源点的出链方向）
   */
  getLinkedSources(file) {
    const seenGroups = /* @__PURE__ */ new Set();
    const linkedSources = [];
    const sourcePaths = this.childMap.get(file.path);
    if (!sourcePaths)
      return linkedSources;
    for (const sourcePath of sourcePaths) {
      const sourceInfo = this.sourceCache.get(sourcePath);
      if (sourceInfo && !seenGroups.has(sourceInfo.group)) {
        linkedSources.push(sourceInfo);
        seenGroups.add(sourceInfo.group);
      }
    }
    return linkedSources;
  }
  /**
   * 通过路径获取关联的所有源点
   */
  getLinkedSourcesByPath(path) {
    return this.getLinkedSourcesByPathInternal(path);
  }
  getLinkedSourcesByPathInternal(path) {
    const seenGroups = /* @__PURE__ */ new Set();
    const linkedSources = [];
    const sourcePaths = this.childMap.get(path);
    if (!sourcePaths)
      return linkedSources;
    for (const sourcePath of sourcePaths) {
      const sourceInfo = this.sourceCache.get(sourcePath);
      if (sourceInfo && !seenGroups.has(sourceInfo.group)) {
        linkedSources.push(sourceInfo);
        seenGroups.add(sourceInfo.group);
      }
    }
    return linkedSources;
  }
};

// colorManager.ts
var ColorManager = class {
  constructor(app, sourceDetector) {
    this.colorCache = /* @__PURE__ */ new Map();
    this.app = app;
    this.sourceDetector = sourceDetector;
  }
  /**
   * 清除缓存
   */
  clearCache() {
    this.colorCache.clear();
  }
  /**
   * 获取节点的颜色信息
   */
  getNodeColorInfo(path) {
    if (this.colorCache.has(path)) {
      return this.colorCache.get(path);
    }
    const sources = this.sourceDetector.getLinkedSourcesByPath(path);
    const colors = sources.map((s) => s.color);
    const info = {
      path,
      sources,
      colors
    };
    this.colorCache.set(path, info);
    return info;
  }
  /**
   * 获取节点应显示的颜色数组
   */
  getNodeColors(path) {
    const info = this.getNodeColorInfo(path);
    return info.colors;
  }
  /**
   * 刷新缓存
   */
  refresh() {
    this.sourceDetector.buildSourceCache();
    this.clearCache();
  }
};

// main.ts
var DEFAULT_SETTINGS2 = {
  ...DEFAULT_SETTINGS,
  enableMultiColor: true
};
function rgbNumberToHex(rgb) {
  return "#" + rgb.toString(16).padStart(6, "0");
}
var GraphSourceColorPlugin = class extends import_obsidian2.Plugin {
  constructor() {
    super(...arguments);
    this.overlayCanvases = /* @__PURE__ */ new Map();
    this.renderRAF = null;
    this.lastColorSync = 0;
    this.removing = false;
  }
  async onload() {
    await this.loadSettings();
    this.app.workspace.onLayoutReady(async () => {
      this.removing = false;
      this.sourceDetector = new SourceDetector(this.app, this.settings);
      this.colorManager = new ColorManager(this.app, this.sourceDetector);
      console.log("[Graph Source Color] Initialized");
      await this.restoreColorsFromGraphJson();
      this.startOverlayRender();
    });
    this.registerEvent(
      this.app.metadataCache.on("changed", () => {
        if (this.colorManager)
          this.colorManager.refresh();
      })
    );
    this.registerEvent(
      this.app.workspace.on("layout-change", () => {
        setTimeout(() => this.setupOverlays(), 500);
      })
    );
    this.addCommand({
      id: "refresh-graph-colors",
      name: "\u5237\u65B0\u56FE\u8C31\u989C\u8272",
      callback: () => {
        if (this.colorManager)
          this.colorManager.refresh();
        new import_obsidian2.Notice("\u56FE\u8C31\u989C\u8272\u5DF2\u5237\u65B0");
      }
    });
    this.addCommand({
      id: "debug-graph-nodes",
      name: "\u8C03\u8BD5\u56FE\u8C31\u8282\u70B9",
      callback: () => this.debugGraphNodes()
    });
    this.addSettingTab(new GraphSourceColorSettingTab(this.app, this));
  }
  onunload() {
    this.removing = true;
    this.cleanupOverlay();
    console.log("[Graph Source Color] Unloaded");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS2, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    if (this.sourceDetector) {
      this.sourceDetector.updateSettings(this.settings);
    }
    if (this.colorManager) {
      this.colorManager.refresh();
    }
    if (!this.settings.enableMultiColor) {
      this.clearOverlaysAndRestoreNodes();
    } else {
      this.setupOverlays();
    }
  }
  async restoreColorsFromGraphJson() {
    var _a, _b, _c, _d, _e;
    if (!this.sourceDetector)
      return;
    try {
      const existingGroups = (_a = await this.readExistingColorGroups()) != null ? _a : [];
      if (existingGroups.length === 0)
        return;
      const pathColorMap = /* @__PURE__ */ new Map();
      for (const cg of existingGroups) {
        if (((_b = cg.query) == null ? void 0 : _b.startsWith("path:")) && ((_c = cg.color) == null ? void 0 : _c.rgb) !== void 0 && ((_d = cg.color) == null ? void 0 : _d.rgb) !== 0 && ((_e = cg.color) == null ? void 0 : _e.rgb) !== 16777215) {
          pathColorMap.set(cg.query.replace("path:", "") + ".md", "#" + cg.color.rgb.toString(16).padStart(6, "0"));
        }
      }
      for (const source of this.sourceDetector.getAllSources()) {
        const color = pathColorMap.get(source.path);
        if (color && color !== "#000000" && color !== "#ffffff") {
          this.settings.groupColors[source.group] = color;
        }
      }
      this.sourceDetector.updateSettings(this.settings);
      this.saveData(this.settings);
    } catch (e) {
      console.warn("[Graph Source Color] Failed to restore colors from graph.json", e);
    }
  }
  async readExistingColorGroups() {
    try {
      const adapter = this.app.vault.adapter;
      const graphJsonPath = this.app.vault.configDir + "/graph.json";
      if (!await adapter.exists(graphJsonPath))
        return null;
      const raw = await adapter.read(graphJsonPath);
      const config = JSON.parse(raw);
      const groups = config.colorGroups;
      if (!Array.isArray(groups))
        return null;
      return groups;
    } catch (e) {
      return null;
    }
  }
  getSourceColorsFromRenderer() {
    const colorMap = /* @__PURE__ */ new Map();
    for (const viewType of ["graph", "localgraph"]) {
      this.app.workspace.getLeavesOfType(viewType).forEach((leaf) => {
        var _a, _b, _c, _d, _e;
        const view = leaf.view;
        const renderer = (_a = view.dataEngine) == null ? void 0 : _a.renderer;
        if (!(renderer == null ? void 0 : renderer.nodes))
          return;
        for (const node of renderer.nodes) {
          if (!node.id || !((_b = this.sourceDetector) == null ? void 0 : _b.isSourcePath(node.id)))
            continue;
          if (((_c = node.circle) == null ? void 0 : _c.tint) !== void 0 && ((_d = node.circle) == null ? void 0 : _d.tint) !== 16777215 && ((_e = node.circle) == null ? void 0 : _e.tint) !== 0) {
            colorMap.set(node.id, rgbNumberToHex(node.circle.tint));
          }
        }
      });
    }
    return colorMap;
  }
  syncColorsFromRenderer() {
    if (!this.sourceDetector)
      return false;
    const tintMap = this.getSourceColorsFromRenderer();
    if (tintMap.size === 0)
      return false;
    let changed = false;
    for (const source of this.sourceDetector.getAllSources()) {
      const tintColor = tintMap.get(source.path);
      if (tintColor && tintColor !== "#000000" && this.settings.groupColors[source.group] !== tintColor) {
        this.settings.groupColors[source.group] = tintColor;
        changed = true;
      }
    }
    if (changed) {
      console.log("[Graph Source Color] Synced from tint:", JSON.stringify(this.settings.groupColors));
      this.sourceDetector.updateSettings(this.settings);
      this.saveData(this.settings);
      this.colorManager.refresh();
    }
    return changed;
  }
  getNodeColorsLive(nodeId, tintMap) {
    if (!this.sourceDetector || !this.colorManager)
      return [];
    const info = this.colorManager.getNodeColorInfo(nodeId);
    if (!info || info.sources.length === 0)
      return [];
    const colorSet = [];
    const seenGroups = /* @__PURE__ */ new Set();
    for (const source of info.sources) {
      if (seenGroups.has(source.group))
        continue;
      seenGroups.add(source.group);
      const tintColor = tintMap.get(source.path);
      const color = tintColor || source.color;
      if (color) {
        colorSet.push(color);
      }
    }
    return colorSet;
  }
  // --- Canvas Overlay ---
  setupOverlays() {
    for (const viewType of ["graph", "localgraph"]) {
      this.app.workspace.getLeavesOfType(viewType).forEach((leaf) => {
        var _a;
        const view = leaf.view;
        const containerEl = view.contentEl;
        if (!containerEl)
          return;
        const key = (_a = leaf.id) != null ? _a : "";
        if (this.overlayCanvases.has(key)) {
          const existing = this.overlayCanvases.get(key);
          if (existing.isConnected)
            return;
          existing.remove();
          this.overlayCanvases.delete(key);
        }
        const canvas = document.createElement("canvas");
        canvas.style.position = "absolute";
        canvas.style.top = "0";
        canvas.style.left = "0";
        canvas.style.width = "100%";
        canvas.style.height = "100%";
        canvas.style.pointerEvents = "none";
        canvas.style.zIndex = "10";
        canvas.className = "graph-source-color-overlay";
        containerEl.style.position = "relative";
        containerEl.appendChild(canvas);
        this.overlayCanvases.set(key, canvas);
        const syncSize = () => {
          var _a2, _b, _c;
          const r = (_b = (_a2 = leaf.view) == null ? void 0 : _a2.dataEngine) == null ? void 0 : _b.renderer;
          const pxRenderer = (_c = r == null ? void 0 : r.px) == null ? void 0 : _c.renderer;
          if (pxRenderer) {
            canvas.width = pxRenderer.width;
            canvas.height = pxRenderer.height;
          } else {
            canvas.width = containerEl.clientWidth;
            canvas.height = containerEl.clientHeight;
          }
        };
        syncSize();
        const ro = new ResizeObserver(() => syncSize());
        ro.observe(containerEl);
        this.register(() => ro.disconnect());
      });
    }
  }
  cleanupOverlay() {
    this.removing = true;
    if (this.renderRAF) {
      cancelAnimationFrame(this.renderRAF);
      this.renderRAF = null;
    }
    this.clearOverlaysAndRestoreNodes();
  }
  clearOverlaysAndRestoreNodes() {
    this.overlayCanvases.forEach((canvas) => {
      const ctx = canvas.getContext("2d");
      if (ctx)
        ctx.clearRect(0, 0, canvas.width, canvas.height);
      canvas.style.display = "none";
      if (canvas.parentNode)
        canvas.parentNode.removeChild(canvas);
    });
    this.overlayCanvases.clear();
    document.querySelectorAll(".graph-source-color-overlay").forEach((el) => el.remove());
    for (const viewType of ["graph", "localgraph"]) {
      this.app.workspace.getLeavesOfType(viewType).forEach((leaf) => {
        var _a;
        const view = leaf.view;
        const containerEl = view.contentEl;
        const renderer = (_a = view.dataEngine) == null ? void 0 : _a.renderer;
        if (!containerEl)
          return;
        containerEl.querySelectorAll("canvas").forEach((canvas) => {
          const el = canvas;
          if (el.style.pointerEvents === "none" && el.style.zIndex === "10") {
            const ctx = canvas.getContext("2d");
            if (ctx)
              ctx.clearRect(0, 0, canvas.width, canvas.height);
            el.style.display = "none";
            if (canvas.parentNode)
              canvas.parentNode.removeChild(canvas);
          }
        });
        if (!(renderer == null ? void 0 : renderer.nodes))
          return;
        for (const node of renderer.nodes) {
          if (node.id && node.circle && node.circle.alpha === 0) {
            node.circle.alpha = 1;
          }
        }
      });
    }
  }
  startOverlayRender() {
    this.setupOverlays();
    const renderLoop = () => {
      if (this.removing)
        return;
      this.renderMultiColorNodes();
      this.renderRAF = requestAnimationFrame(renderLoop);
    };
    this.renderRAF = requestAnimationFrame(renderLoop);
  }
  renderMultiColorNodes() {
    if (!this.colorManager || !this.settings.enableMultiColor)
      return;
    const now = Date.now();
    if (now - this.lastColorSync > 2e3) {
      this.syncColorsFromRenderer();
      this.lastColorSync = now;
    }
    const tintMap = this.getSourceColorsFromRenderer();
    for (const viewType of ["graph", "localgraph"]) {
      this.app.workspace.getLeavesOfType(viewType).forEach((leaf) => {
        var _a, _b, _c;
        const view = leaf.view;
        const dataEngine = view.dataEngine;
        const renderer = dataEngine == null ? void 0 : dataEngine.renderer;
        if (!(renderer == null ? void 0 : renderer.nodes))
          return;
        const key = (_a = leaf.id) != null ? _a : "";
        const canvas = this.overlayCanvases.get(key);
        if (!canvas)
          return;
        const ctx = canvas.getContext("2d");
        if (!ctx)
          return;
        const pxRenderer = (_b = renderer.px) == null ? void 0 : _b.renderer;
        if (pxRenderer) {
          const pw = pxRenderer.width;
          const ph = pxRenderer.height;
          if (canvas.width !== pw || canvas.height !== ph) {
            canvas.width = pw;
            canvas.height = ph;
          }
        }
        ctx.clearRect(0, 0, canvas.width, canvas.height);
        const scale = renderer.scale || 1;
        const panX = renderer.panX || 0;
        const panY = renderer.panY || 0;
        const nodeScale = renderer.nodeScale || 1;
        for (const node of renderer.nodes) {
          if (!node.id)
            continue;
          if ((_c = this.sourceDetector) == null ? void 0 : _c.isSourcePath(node.id)) {
            if (node.circle && node.circle.alpha === 0)
              node.circle.alpha = 1;
            continue;
          }
          const colors = this.getNodeColorsLive(node.id, tintMap);
          if (colors.length <= 1) {
            if (node.circle && node.circle.alpha === 0)
              node.circle.alpha = 1;
            continue;
          }
          let screenX, screenY, radius;
          if (node.circle && typeof node.circle.getBounds === "function") {
            const bounds = node.circle.getBounds();
            screenX = bounds.x + bounds.width / 2;
            screenY = bounds.y + bounds.height / 2;
            radius = bounds.width / 2;
          } else {
            screenX = node.x * scale + panX;
            screenY = node.y * scale + panY;
            radius = 3 * nodeScale * scale;
          }
          if (node.circle) {
            node.circle.alpha = 0;
          }
          this.drawMultiColorNode(ctx, screenX, screenY, radius, colors);
        }
      });
    }
  }
  drawMultiColorNode(ctx, x, y, radius, colors) {
    if (colors.length === 2) {
      ctx.beginPath();
      ctx.arc(x, y, radius, Math.PI / 2, 3 * Math.PI / 2);
      ctx.fillStyle = colors[0];
      ctx.fill();
      ctx.beginPath();
      ctx.arc(x, y, radius, -Math.PI / 2, Math.PI / 2);
      ctx.fillStyle = colors[1];
      ctx.fill();
    } else {
      const sliceAngle = 2 * Math.PI / colors.length;
      colors.forEach((color, i) => {
        const startAngle = -Math.PI / 2 + i * sliceAngle;
        const endAngle = startAngle + sliceAngle;
        ctx.beginPath();
        ctx.moveTo(x, y);
        ctx.arc(x, y, radius, startAngle, endAngle);
        ctx.closePath();
        ctx.fillStyle = color;
        ctx.fill();
      });
    }
    ctx.beginPath();
    ctx.arc(x, y, radius, 0, 2 * Math.PI);
    ctx.strokeStyle = "#333333";
    ctx.lineWidth = 1;
    ctx.stroke();
  }
  // --- Debug ---
  debugGraphNodes() {
    console.log("=== Graph Source Color Debug ===");
    console.log("Plugin groupColors:", JSON.stringify(this.settings.groupColors));
    const tintMap = this.getSourceColorsFromRenderer();
    console.log("PixiJS tint colors:", Object.fromEntries(tintMap));
    if (this.colorManager) {
      const files = this.app.vault.getMarkdownFiles();
      for (const file of files) {
        const liveColors = this.getNodeColorsLive(file.path, tintMap);
        if (liveColors.length > 0) {
          const tag = liveColors.length > 1 ? "MULTI" : "single";
          console.log(`  [${tag}] "${file.path}": colors=${JSON.stringify(liveColors)}`);
        }
      }
    }
    for (const [key, canvas] of this.overlayCanvases) {
      console.log(`Overlay canvas "${key}": ${canvas.width}x${canvas.height}`);
    }
    new import_obsidian2.Notice("\u8C03\u8BD5\u4FE1\u606F\u5DF2\u8F93\u51FA\u5230\u63A7\u5236\u53F0");
  }
};
var GraphSourceColorSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "\u56FE\u8C31\u6E90\u70B9\u7740\u8272\u8BBE\u7F6E" });
    new import_obsidian2.Setting(containerEl).setName("\u542F\u7528\u591A\u8272\u8282\u70B9").setDesc("\u4E3A\u94FE\u63A5\u591A\u4E2A\u6E90\u70B9\u7684\u7B14\u8BB0\u663E\u793A\u591A\u8272\u8282\u70B9").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableMultiColor).onChange(async (value) => {
      this.plugin.settings.enableMultiColor = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("\u6E90\u70B9\u6587\u4EF6\u5939").setDesc("\u5B58\u653E\u6E90\u70B9\u7B14\u8BB0\u7684\u6587\u4EF6\u5939\u8DEF\u5F84").addText((text) => text.setValue(this.plugin.settings.sourceFolder).onChange(async (value) => {
      this.plugin.settings.sourceFolder = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "\u5206\u7EC4\u989C\u8272" });
    containerEl.createEl("p", {
      text: "\u6E90\u8282\u70B9\u989C\u8272\u8BF7\u5728 Obsidian \u56FE\u8C31\u8BBE\u7F6E\u4E2D\u4FEE\u6539\uFF0C\u4FEE\u6539\u540E\u5B50\u8282\u70B9\u989C\u8272\u4F1A\u81EA\u52A8\u8054\u52A8",
      cls: "setting-item-description"
    });
  }
};
